import pandas as pd
import anndata

def expression_matrix_filter(expression_matrix, 
                             feature_matrix_label, 
                             cell_extended,  
                             region_of_interest = 'MO-FRP', 
                             neurotransmitters = ['GABA', 'Glut']):
    '''
    Generates an anndata object that has all of the metadata information for cluster and ROI. Because
    of how the anndata files are saved, this corresponds just to a feature_matrix. 
    I don't know why the number of entries for a feature matrix in the metadata
    is smaller than in the data by about 1K, but I've decided to not really care for
    now.  I've made a note and I'll probably raise an issue on their repo (scary)

    Args: 
        expression_matrix(anndata): a feature_matrix as read by abc_cache
        feature_matrix_label(str): a string indicating the name of the feature matrix on the server. 
        cell_extended(df): a pandas df generated by build_extended_metadata
        other params: filters for the kinds of cell you want to keep. 

    Out: 
        filtered_expression_matrix(anndata): an anndata object with massive metadata. 
    '''
    #Build metadata
    pred = (cell_extended['feature_matrix_label'] == feature_matrix_label)
    cell_filtered = cell_extended[pred]
    print('Cell labels in metadata:')
    print(len(cell_filtered.index))
    print('Cell labels in cells:')
    print(len(expression_matrix.obs.index))

    #Asserting labels are unique
    assert expression_matrix.obs.index.is_unique, "expression_matrix.obs has duplicate cell_label indices."
    assert cell_filtered.index.is_unique, "Metadata df has duplicate cell_label indices."

    #Dropping columns that are in both expression_matrix.obs and metadata
    #to allow joining of the two by cell label. 
    cell_filtered = cell_filtered.drop(columns = 'library_label')
    cell_filtered = cell_filtered.drop(columns = 'cell_barcode')

    #joining
    expression_matrix.obs = expression_matrix.obs.join(cell_filtered, how='left')

    #filtering for the right ROI and neurotransmitter
    filtered_expression_matrix = expression_matrix[(expression_matrix.obs['region_of_interest_acronym']==region_of_interest) & (expression_matrix.obs['neurotransmitter'].isin(neurotransmitters))]

    return filtered_expression_matrix

def build_extended_metadata(abc_cache, directory = 'WMB-10X'):
    '''
    Gets the right kind of metadata from the cache as a dataframe. 
    Adds the ROI information and cluster information to the df. They're
    originally stored as different files, but we want to filter by
    all of these and include subclass information. 

        Out: cell_extended (df): metadata for every cell in the directory
    '''
    #get basic metadata
    cell = abc_cache.get_metadata_dataframe(
    directory=directory,
    file_name='cell_metadata',
    dtype={'cell_label': str}
    )  
    cell.set_index('cell_label', inplace=True)

    #add region of interest
    roi = abc_cache.get_metadata_dataframe(directory=directory, file_name='region_of_interest_metadata')
    roi.set_index('acronym', inplace=True)
    roi.rename(columns={'order': 'region_of_interest_order',
                        'color_hex_triplet': 'region_of_interest_color'},
            inplace=True)
    
    #add clustering
    cluster_details = abc_cache.get_metadata_dataframe(
    directory='WMB-taxonomy',
    file_name='cluster_to_cluster_annotation_membership_pivoted',
    keep_default_na=False
    )
    cluster_details.set_index('cluster_alias', inplace=True)

    #merge
    cell_extended = cell.join(cluster_details, on='cluster_alias')
    cell_extended = cell_extended.join(roi[['region_of_interest_order', 'region_of_interest_color']], on='region_of_interest_acronym')

    return cell_extended

def generate_csv(expression_matrix, download_base, region_of_interest, neurotransmitters):

    # Extract the gene expression data (X matrix) and convert it to a DataFrame
    df = pd.DataFrame(expression_matrix.X.toarray(), columns=expression_matrix.var_names)

    # Add the 'subclass' and 'cluster' columns from the `obs` DataFrame to `df`
    df['subclass'] = expression_matrix.obs['subclass']
    df['cluster'] = expression_matrix.obs['cluster']

    gene_mapping = pd.DataFrame({
        'gene_index': range(len(expression_matrix.var)),
        'gene_identifier': expression_matrix.var_names,
        'gene_symbol': expression_matrix.var.gene_symbol.values
    })

    # Define the path to save the DataFrame as a CSV

    df_path = download_base / f'WMB_processed_{region_of_interest}_{neurotransmitters}.csv'

    df.to_csv(df_path, index=False)

    gene_names = expression_matrix.var.gene_symbol

    gene_path = download_base / f'gene_mapping_{region_of_interest}_{neurotransmitters}.csv'

    gene_mapping.to_csv(gene_path, index=False)
    
    #save the gene names thing

    return df, gene_names

def read_yao_2023(download_base, region_of_interest = 'MO-FRP', neurotransmitters = ['GABA', 'Glut']):
    '''
    If you have already created the expression matrix once, use this function to read it. 
    '''
    csv_path = download_base / f'WMB_processed_{region_of_interest}_{neurotransmitters}.csv'
    gene_path = download_base / f'gene_mapping_{region_of_interest}_{neurotransmitters}.csv'

    df = pd.read_csv(csv_path)
    gene_names = pd.read_csv(gene_path)

    return df, gene_names

def main_yao_2023(abc_cache, 
                  directory, 
                  filename_list, 
                  download_base,
                  region_of_interest = 'MO-FRP', 
                  neurotransmitters = ['GABA', 'Glut']):
    
    '''
    Accesses the Allen dataset on Yao et. al 2023, "A high-resolution 
    transcriptomic and spatial atlas of cell types in the 
    whole mouse brain". Downloads relevant data in their format
    according to abc_atlas_access, which is their package to interact with
    the dataset and generates a csv with subclass and cluster layer. 
    The taxonomic denominations are according to the paper. 

    Args: 
        abc_cache(class): generated by the Allen abc_cache package

        directory(str): the directory in the Allen server, generally WMB-10Xv3
        for 10X scRNAseq. 

        filename_list(list of str): the list of expression matrix that we want

        download_base(Path): the location of the abc_cache. This is also where
        the outputs will be saved. 

        region_of_interest(str): one of the dissected regions of the
        atlas. The pipeline will only keep data from there. 
        
        neurotransmitters(list of str): neurotransmitters to filter the dataset by. 

    Out: 
        df: cells x genes dataframe. Indexed by cell_label and Ensembl
        gene ID, like the Allen data. Contains two additional columns that
        indicate the subclass and cluster identity of each cell, for the pick_genes 
        pipeline. 

        gene_names: indexed by Ensembl ID, the names of the genes. 
    '''

    filelist = []

    for filename in filename_list:
        
        print('Downloading or accessing data. If not already in the cache, could be long')
        file = abc_cache.get_data_path(directory = directory, 
                                        file_name = f'{filename}/raw')
        
        expression_matrix = anndata.read_h5ad(file, backed='r')

        print('Building metadata')
        cell_extended = build_extended_metadata(abc_cache)

        print('Filtering data with roi/neurotransmitter')
        filtered_expression_matrix = expression_matrix_filter(expression_matrix, 
                                    feature_matrix_label = filename, 
                                    cell_extended = cell_extended,  
                                    region_of_interest = region_of_interest, 
                                    neurotransmitters = neurotransmitters)
        filelist.append(filtered_expression_matrix)

    filelist = tuple(filelist)
    assert filelist[0].var.equals(filelist[1].var), "The .var DataFrames are not identical."

    #merging the aadata with 'unique' strategy preserves metadata in obs and var because there
    #is only one possible value for it (a counterexample is the sum of all values for)
    #a variable, or its mean, which change depending on the subset). In our case, 
    #it's the gene names, so 'unique' for each variable. 
    
    concat_expression_matrix = anndata.concat([filelist[0],filelist[1]], merge = 'unique')

    print('Extracting and generating csv')
    df, gene_names = generate_csv(concat_expression_matrix, 
                                  download_base = download_base, 
                                  region_of_interest=region_of_interest, 
                                  neurotransmitters=neurotransmitters)

    return df, gene_names
    
